### ISSUE TITLE
页面双击 console 偶现异常

### ISSUE THREAD

**Issue by 521xueweihan** [HelloGitHub-Team/geese#48]
## 前端 console 偶现异常
```
VM238817:50 Uncaught TypeError: (event.target.className || "").indexOf is not a function
    at onDoubleClick (eval at success (kernel.js:233:37), <anonymous>:50:48)
    at dispatch (jquery.js:5237:49)
    at elemData.handle (jquery.js:5044:47)
```

**Comment by 521xueweihan** [comment]
翻译插件导致，非 geese 问题。
